### ISSUE TITLE
Consider adding a split line to the top bar.

### ISSUE THREAD

**Issue by sihaixianyu** [qinains/theme-hbuilderx-soft-green-light#13]
It's difficult to determine the boundary between breadcrum adn file tab page.
<img width="455" alt="image" src="https://user-images.githubusercontent.com/32222479/232974715-a64fce76-539a-48e9-9981-7de3f96853e6.png">

**Comment by qinains** [comment]
是在哪添加这个分割线呢?

**Comment by sihaixianyu** [comment]
文件标签页和代码框之间，其他主题都比较清楚，大佬有空加一加？

**Comment by qinains** [comment]
v1.0.5已经添加

**Comment by sihaixianyu** [comment]
![3979E2606B6AD2068D6CDB287926FBCA](https://github.com/qinains/theme-hbuilderx-soft-green-light/assets/32222479/04d93bcd-61d9-4f13-8a4e-00ec195bbd3c)
