### ISSUE TITLE
terminal color

### ISSUE THREAD

**Issue by engvuchen** [qinains/theme-hbuilderx-soft-green-light#2]
vscode 终端，颜色配置上，npm/git 等命令前缀，和背景色难以区分；

![image](https://user-images.githubusercontent.com/31369318/90713050-051f3a00-e2d7-11ea-9288-65267f954be8.png)

**Comment by qinains** [comment]
有推荐的色值吗？

**Comment by qinains** [comment]
已经更新，试试 @zhiqiang404

**Comment by engvuchen** [comment]
可以，感谢🌹

**Comment by qinains** [comment]
有问题随时提哈
