### ISSUE TITLE
The difference between a plugin theme and a native theme

### ISSUE THREAD

**Issue by engvuchen** [qinains/theme-hbuilderx-soft-green-light#3]
![image](https://user-images.githubusercontent.com/31369318/91118397-70944d80-e6c3-11ea-8f68-6772b7bd4f1b.png)

通过对比插件主题（vscode），原生主题（HbuilderX），个人感觉原生主题的对比度比较高，除却字体大小、种类影响，插件主题应该修改了某些颜色？

可否告知为何不简单地应用HbuilderX的原生主题？

**Comment by qinains** [comment]
用取色器拿的色值，有部分可能不太对。你可以修改，然后提交一个pr

**Comment by engvuchen** [comment]
HBuilderX\plugins\theme-default\themes\default;

若安装了HBuildeX，可以从这里提取出主题；
虽然颜色配置文件的 JSON 结构和 vscode 的配置差不多，但是很多属性都不被支持了；

作者有空就看下呗~

**Comment by qinains** [comment]
你想支持哪些呢？有一些属性的确是不对齐的。需要一个个修改
