### ISSUE TITLE
The healthiest theme for your eyes!

### ISSUE THREAD

**Issue by Remote-version-git** [qinains/theme-hbuilderx-soft-green-light#4]
This theme very healthy but I often use sublime text 3.

If has a same theme for sublime text 3, That's Great.

**Comment by qinains** [comment]
对sublime text 3 不太熟。你可以尝试参照这个方法自己定制看看 [https://www.pianshen.com/article/53911165133/](https://www.pianshen.com/article/53911165133/) 。用取色器取我里边的颜色，或者直接去 [https://github.com/qinains/theme-hbuilderx-soft-green-light/blob/master/themes/hbuilderx-soft-green-light-color-theme.json](https://github.com/qinains/theme-hbuilderx-soft-green-light/blob/master/themes/hbuilderx-soft-green-light-color-theme.json) 这个文件找对应的色值。当然你做出来之后，贡献给社区，那是最棒的啦

**Comment by Remote-version-git** [comment]
That's a good idea, I will do it.
